Allow a date range to be selected for calculations
supermetrics-public/php-assignment pull request #12
Opened 2022-12-19 13:06 UTC by pawel-lewtak

# Allow a date range to be given in UI

This date range would be later used in all stats calculations.

![image](https://user-images.githubusercontent.com/5846223/208432745-ca344898-6d91-440b-9216-c4bc64abc0d9.png)

2022-12-19 13:14 UTC, srakhmanchuk approved these changes

2022-12-19 13:49 UTC, pawel-lewtak commented
@niklam could you please have a look at this PR and merge it if you're ok with it?

2022-12-21 05:57 UTC, niklam requested changes
Please format the files in a consistent manner.

Now we have both

```php
$foo = 'value';
$foobar = 'value';
```

and

```php
$foo    = 'value';
$foobar = 'value';
```

The latter is the style we usually have, and which is in the other files.

2023-01-04 09:19 UTC, niklam approved these changes

2023-01-04 09:20 UTC, merged